// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: channels.sql

package sqlc

import (
	"context"
	"time"
)

const addChannelSignature = `-- name: AddChannelSignature :exec
UPDATE channels
SET signature = $2
WHERE id = $1
`

type AddChannelSignatureParams struct {
	ID        int64
	Signature []byte
}

func (q *Queries) AddChannelSignature(ctx context.Context, arg AddChannelSignatureParams) error {
	_, err := q.db.ExecContext(ctx, addChannelSignature, arg.ID, arg.Signature)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE channel_id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, channelID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, channelID)
	return err
}

const deleteChannelFeature = `-- name: DeleteChannelFeature :exec
DELETE FROM channel_features
WHERE channel_id = $1
  AND feature = $2
`

type DeleteChannelFeatureParams struct {
	ChannelID int64
	Feature   int32
}

func (q *Queries) DeleteChannelFeature(ctx context.Context, arg DeleteChannelFeatureParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelFeature, arg.ChannelID, arg.Feature)
	return err
}

const deleteExtraChannelType = `-- name: DeleteExtraChannelType :exec
DELETE FROM channel_extra_types
WHERE channel_id = $1
  AND type = $2
`

type DeleteExtraChannelTypeParams struct {
	ChannelID int64
	Type      int64
}

func (q *Queries) DeleteExtraChannelType(ctx context.Context, arg DeleteExtraChannelTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteExtraChannelType, arg.ChannelID, arg.Type)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, channel_id, outpoint, node_id_1, node_id_2, capacity, signature, created_at
FROM channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Outpoint,
		&i.NodeID1,
		&i.NodeID2,
		&i.Capacity,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelByChanID = `-- name: GetChannelByChanID :one
SELECT id, channel_id, outpoint, node_id_1, node_id_2, capacity, signature, created_at
FROM channels
WHERE channel_id = $1
`

func (q *Queries) GetChannelByChanID(ctx context.Context, channelID int64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByChanID, channelID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Outpoint,
		&i.NodeID1,
		&i.NodeID2,
		&i.Capacity,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelByOutpoint = `-- name: GetChannelByOutpoint :one
SELECT id, channel_id, outpoint, node_id_1, node_id_2, capacity, signature, created_at
FROM channels
WHERE outpoint = $1
`

func (q *Queries) GetChannelByOutpoint(ctx context.Context, outpoint string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByOutpoint, outpoint)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Outpoint,
		&i.NodeID1,
		&i.NodeID2,
		&i.Capacity,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelFeatures = `-- name: GetChannelFeatures :many
SELECT channel_id, feature
FROM channel_features
WHERE channel_id = $1
`

func (q *Queries) GetChannelFeatures(ctx context.Context, channelID int64) ([]ChannelFeature, error) {
	rows, err := q.db.QueryContext(ctx, getChannelFeatures, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelFeature
	for rows.Next() {
		var i ChannelFeature
		if err := rows.Scan(&i.ChannelID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExtraChannelTypes = `-- name: GetExtraChannelTypes :many
SELECT channel_id, type, value
FROM channel_extra_types
WHERE channel_id = $1
`

func (q *Queries) GetExtraChannelTypes(ctx context.Context, channelID int64) ([]ChannelExtraType, error) {
	rows, err := q.db.QueryContext(ctx, getExtraChannelTypes, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelExtraType
	for rows.Next() {
		var i ChannelExtraType
		if err := rows.Scan(&i.ChannelID, &i.Type, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (
    channel_id, outpoint, node_id_1, node_id_2, capacity, signature, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id
`

type InsertChannelParams struct {
	ChannelID int64
	Outpoint  string
	NodeID1   int64
	NodeID2   int64
	Capacity  int64
	Signature []byte
	CreatedAt time.Time
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChannel,
		arg.ChannelID,
		arg.Outpoint,
		arg.NodeID1,
		arg.NodeID2,
		arg.Capacity,
		arg.Signature,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChannelFeature = `-- name: InsertChannelFeature :exec
INSERT INTO channel_features (
    channel_id, feature
) VALUES (
    $1, $2
)
`

type InsertChannelFeatureParams struct {
	ChannelID int64
	Feature   int32
}

func (q *Queries) InsertChannelFeature(ctx context.Context, arg InsertChannelFeatureParams) error {
	_, err := q.db.ExecContext(ctx, insertChannelFeature, arg.ChannelID, arg.Feature)
	return err
}

const isPublicNode = `-- name: IsPublicNode :one
SELECT EXISTS (
    SELECT 1
    FROM channels
    WHERE (node_id_1 = $1 OR node_id_2 = $1)
      AND signature IS NOT NULL
) AS is_public
`

func (q *Queries) IsPublicNode(ctx context.Context, nodeID1 int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isPublicNode, nodeID1)
	var is_public bool
	err := row.Scan(&is_public)
	return is_public, err
}

const listNodeChannels = `-- name: ListNodeChannels :many
SELECT id, channel_id, outpoint, node_id_1, node_id_2, capacity, signature, created_at
FROM channels
WHERE node_id_1 = $1
   OR node_id_2 = $1
`

func (q *Queries) ListNodeChannels(ctx context.Context, nodeID1 int64) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listNodeChannels, nodeID1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Outpoint,
			&i.NodeID1,
			&i.NodeID2,
			&i.Capacity,
			&i.Signature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelExtraType = `-- name: UpsertChannelExtraType :exec
INSERT INTO channel_extra_types (channel_id, type, value)
VALUES ($1, $2, $3)
ON CONFLICT (type, channel_id)
    DO UPDATE SET value = EXCLUDED.value
`

type UpsertChannelExtraTypeParams struct {
	ChannelID int64
	Type      int64
	Value     []byte
}

func (q *Queries) UpsertChannelExtraType(ctx context.Context, arg UpsertChannelExtraTypeParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelExtraType, arg.ChannelID, arg.Type, arg.Value)
	return err
}
