// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: channels.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteChannelByChanID = `-- name: DeleteChannelByChanID :exec
DELETE FROM channels
WHERE channel_id = $1
`

func (q *Queries) DeleteChannelByChanID(ctx context.Context, channelID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannelByChanID, channelID)
	return err
}

const getChanDBIDBYChanID = `-- name: GetChanDBIDBYChanID :one
SELECT id
FROM channels
WHERE channel_id = $1
`

func (q *Queries) GetChanDBIDBYChanID(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChanDBIDBYChanID, channelID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getChanDBIDByChanID = `-- name: GetChanDBIDByChanID :one
SELECT id
FROM channels
WHERE channel_id = $1
`

func (q *Queries) GetChanDBIDByChanID(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChanDBIDByChanID, channelID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getChanDBIDByOutpoint = `-- name: GetChanDBIDByOutpoint :one
SELECT id
FROM channels
WHERE outpoint = $1
`

func (q *Queries) GetChanDBIDByOutpoint(ctx context.Context, outpoint string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChanDBIDByOutpoint, outpoint)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getChannel = `-- name: GetChannel :one
SELECT
    c.id,
    c.channel_id,
    c.outpoint,
    c.node_id_1,
    c.node_id_2,
    c.capacity,
    c.serialised_announcement,
    COALESCE(sc.announced, true) AS announced
FROM
    channels c
        LEFT JOIN
    source_channels sc ON c.id = sc.channel_id
WHERE
    c.id = $1
`

type GetChannelRow struct {
	ID                     int64
	ChannelID              int64
	Outpoint               string
	NodeID1                int64
	NodeID2                int64
	Capacity               sql.NullInt64
	SerialisedAnnouncement []byte
	Announced              bool
}

func (q *Queries) GetChannel(ctx context.Context, id int64) (GetChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Outpoint,
		&i.NodeID1,
		&i.NodeID2,
		&i.Capacity,
		&i.SerialisedAnnouncement,
		&i.Announced,
	)
	return i, err
}

const getChannelFeatures = `-- name: GetChannelFeatures :many
SELECT channel_id, feature
FROM channel_features
WHERE channel_id = $1
`

func (q *Queries) GetChannelFeatures(ctx context.Context, channelID int64) ([]ChannelFeature, error) {
	rows, err := q.db.QueryContext(ctx, getChannelFeatures, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelFeature
	for rows.Next() {
		var i ChannelFeature
		if err := rows.Scan(&i.ChannelID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (
    channel_id, outpoint, node_id_1, node_id_2, capacity, serialised_announcement
) VALUES (
     $1, $2, $3, $4, $5, $6
) RETURNING id
`

type InsertChannelParams struct {
	ChannelID              int64
	Outpoint               string
	NodeID1                int64
	NodeID2                int64
	Capacity               sql.NullInt64
	SerialisedAnnouncement []byte
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChannel,
		arg.ChannelID,
		arg.Outpoint,
		arg.NodeID1,
		arg.NodeID2,
		arg.Capacity,
		arg.SerialisedAnnouncement,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChannelFeature = `-- name: InsertChannelFeature :exec
INSERT INTO channel_features (
    channel_id, feature
) VALUES (
             $1, $2
)
`

type InsertChannelFeatureParams struct {
	ChannelID int64
	Feature   int32
}

func (q *Queries) InsertChannelFeature(ctx context.Context, arg InsertChannelFeatureParams) error {
	_, err := q.db.ExecContext(ctx, insertChannelFeature, arg.ChannelID, arg.Feature)
	return err
}

const insertSourceChannel = `-- name: InsertSourceChannel :exec
INSERT INTO source_channels (
    channel_id, announced
) VALUES (
    $1, $2
) ON CONFLICT (channel_id)
DO UPDATE SET announced=$2
`

type InsertSourceChannelParams struct {
	ChannelID int64
	Announced bool
}

func (q *Queries) InsertSourceChannel(ctx context.Context, arg InsertSourceChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertSourceChannel, arg.ChannelID, arg.Announced)
	return err
}

const setSourceChannelAnnounced = `-- name: SetSourceChannelAnnounced :execresult
UPDATE source_channels
SET announced = $2
WHERE channel_id = $1
`

type SetSourceChannelAnnouncedParams struct {
	ChannelID int64
	Announced bool
}

func (q *Queries) SetSourceChannelAnnounced(ctx context.Context, arg SetSourceChannelAnnouncedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setSourceChannelAnnounced, arg.ChannelID, arg.Announced)
}

const updateChannel = `-- name: UpdateChannel :exec
UPDATE channels
SET serialised_announcement = $2
WHERE id = $1
`

type UpdateChannelParams struct {
	ID                     int64
	SerialisedAnnouncement []byte
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) error {
	_, err := q.db.ExecContext(ctx, updateChannel, arg.ID, arg.SerialisedAnnouncement)
	return err
}
