// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: channel_policies.sql

package sqlc

import (
	"context"
)

const getChannelPolicy = `-- name: GetChannelPolicy :one
SELECT cp.id, cp.channel_id, cp.block_height, cp.disable_flags, cp.second_peer, cp.timelock, cp.fee_ppm, cp.base_fee_msat, cp.max_htlc_msat, cp.min_htlc_msat, cp.serialised_announcement
FROM channel_policies cp
JOIN channels c ON cp.channel_id = c.id
WHERE c.channel_id = $1 AND cp.second_peer = $2
`

type GetChannelPolicyParams struct {
	ChannelID  int64
	SecondPeer bool
}

func (q *Queries) GetChannelPolicy(ctx context.Context, arg GetChannelPolicyParams) (ChannelPolicy, error) {
	row := q.db.QueryRowContext(ctx, getChannelPolicy, arg.ChannelID, arg.SecondPeer)
	var i ChannelPolicy
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.BlockHeight,
		&i.DisableFlags,
		&i.SecondPeer,
		&i.Timelock,
		&i.FeePpm,
		&i.BaseFeeMsat,
		&i.MaxHtlcMsat,
		&i.MinHtlcMsat,
		&i.SerialisedAnnouncement,
	)
	return i, err
}

const insertChannelUpdate = `-- name: InsertChannelUpdate :one
INSERT INTO channel_policies (
    channel_id,
    block_height,
    disable_flags,
    second_peer,
    timelock,
    fee_ppm,
    base_fee_msat,
    max_htlc_msat,
    min_htlc_msat,
    serialised_announcement
) VALUES (
    $1,
 $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
) RETURNING id
`

type InsertChannelUpdateParams struct {
	ChannelID              int64
	BlockHeight            int32
	DisableFlags           int32
	SecondPeer             bool
	Timelock               int32
	FeePpm                 int64
	BaseFeeMsat            int64
	MaxHtlcMsat            int64
	MinHtlcMsat            int64
	SerialisedAnnouncement []byte
}

func (q *Queries) InsertChannelUpdate(ctx context.Context, arg InsertChannelUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChannelUpdate,
		arg.ChannelID,
		arg.BlockHeight,
		arg.DisableFlags,
		arg.SecondPeer,
		arg.Timelock,
		arg.FeePpm,
		arg.BaseFeeMsat,
		arg.MaxHtlcMsat,
		arg.MinHtlcMsat,
		arg.SerialisedAnnouncement,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateChannelPolicy = `-- name: UpdateChannelPolicy :exec
UPDATE channel_policies
SET
    block_height = $2,
    disable_flags = $3,
    timelock = $4,
    fee_ppm = $5,
    base_fee_msat = $6,
    max_htlc_msat = $7,
    min_htlc_msat = $8,
    serialised_announcement = $9
WHERE id = $1
`

type UpdateChannelPolicyParams struct {
	ID                     int64
	BlockHeight            int32
	DisableFlags           int32
	Timelock               int32
	FeePpm                 int64
	BaseFeeMsat            int64
	MaxHtlcMsat            int64
	MinHtlcMsat            int64
	SerialisedAnnouncement []byte
}

func (q *Queries) UpdateChannelPolicy(ctx context.Context, arg UpdateChannelPolicyParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelPolicy,
		arg.ID,
		arg.BlockHeight,
		arg.DisableFlags,
		arg.Timelock,
		arg.FeePpm,
		arg.BaseFeeMsat,
		arg.MaxHtlcMsat,
		arg.MinHtlcMsat,
		arg.SerialisedAnnouncement,
	)
	return err
}
