// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type AmpSubInvoice struct {
	SetID       []byte
	State       int16
	CreatedAt   time.Time
	SettledAt   sql.NullTime
	SettleIndex sql.NullInt64
	InvoiceID   int64
}

type AmpSubInvoiceHtlc struct {
	InvoiceID  int64
	SetID      []byte
	HtlcID     int64
	RootShare  []byte
	ChildIndex int64
	Hash       []byte
	Preimage   []byte
}

type Channel struct {
	ID        int64
	ChannelID int64
	Outpoint  string
	NodeID1   int64
	NodeID2   int64
	Capacity  int64
	Signature []byte
	CreatedAt time.Time
}

type ChannelExtraType struct {
	ChannelID int64
	Type      int64
	Value     []byte
}

type ChannelFeature struct {
	ChannelID int64
	Feature   int32
}

type ChannelPolicy struct {
	ID           int64
	ChannelID    int64
	SecondPeer   bool
	BlockHeight  int32
	DisableFlags int32
	Timelock     int32
	FeePpm       int64
	BaseFeeMsat  int64
	MaxHtlcMsat  int64
	MinHtlcMsat  int64
	Signature    []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ChannelPolicyExtraType struct {
	ChannelPolicyID int64
	Type            int64
	Value           []byte
}

type ClosedScid struct {
	ChannelID int64
	CreatedAt time.Time
}

type Invoice struct {
	ID                 int64
	Hash               []byte
	Preimage           []byte
	SettleIndex        sql.NullInt64
	SettledAt          sql.NullTime
	Memo               sql.NullString
	AmountMsat         int64
	CltvDelta          sql.NullInt32
	Expiry             int32
	PaymentAddr        []byte
	PaymentRequest     sql.NullString
	PaymentRequestHash []byte
	State              int16
	AmountPaidMsat     int64
	IsAmp              bool
	IsHodl             bool
	IsKeysend          bool
	CreatedAt          time.Time
}

type InvoiceEvent struct {
	ID        int64
	AddedAt   time.Time
	EventType int32
	InvoiceID int64
	SetID     []byte
}

type InvoiceEventType struct {
	ID          int64
	Description string
}

type InvoiceFeature struct {
	Feature   int32
	InvoiceID int64
}

type InvoiceHtlc struct {
	ID           int64
	ChanID       string
	HtlcID       int64
	AmountMsat   int64
	TotalMppMsat sql.NullInt64
	AcceptHeight int32
	AcceptTime   time.Time
	ExpiryHeight int32
	State        int16
	ResolveTime  sql.NullTime
	InvoiceID    int64
}

type InvoiceHtlcCustomRecord struct {
	Key    int64
	Value  []byte
	HtlcID int64
}

type InvoicePaymentHash struct {
	ID       int64
	AddIndex int64
	Hash     []byte
}

type InvoiceSequence struct {
	Name         string
	CurrentValue int64
}

type MigrationTracker struct {
	Version       int32
	MigrationTime time.Time
}

type Node struct {
	ID          int64
	PubKey      []byte
	Alias       sql.NullString
	BlockHeight int64
	Signature   []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type NodeAddress struct {
	NodeID  int64
	Type    int16
	Address string
}

type NodeExtraType struct {
	NodeID int64
	Type   int64
	Value  []byte
}

type NodeFeature struct {
	NodeID  int64
	Feature int32
}

type SourceNode struct {
	NodeID int64
}

type ZombieChannel struct {
	ChannelID int64
	NodeKey1  []byte
	NodeKey2  []byte
	CreatedAt time.Time
}
