// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: nodes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes
WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const deleteNodeAddress = `-- name: DeleteNodeAddress :exec
DELETE FROM node_addresses
WHERE node_id = $1
  AND address = $2
`

type DeleteNodeAddressParams struct {
	NodeID  int64
	Address string
}

func (q *Queries) DeleteNodeAddress(ctx context.Context, arg DeleteNodeAddressParams) error {
	_, err := q.db.ExecContext(ctx, deleteNodeAddress, arg.NodeID, arg.Address)
	return err
}

const deleteNodeFeature = `-- name: DeleteNodeFeature :exec
DELETE FROM node_features
WHERE node_id = $1
AND feature = $2
`

type DeleteNodeFeatureParams struct {
	NodeID  int64
	Feature int32
}

func (q *Queries) DeleteNodeFeature(ctx context.Context, arg DeleteNodeFeatureParams) error {
	_, err := q.db.ExecContext(ctx, deleteNodeFeature, arg.NodeID, arg.Feature)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, pub_key, block_height, alias, serialised_announcement
FROM nodes
WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PubKey,
		&i.BlockHeight,
		&i.Alias,
		&i.SerialisedAnnouncement,
	)
	return i, err
}

const getNodeAddresses = `-- name: GetNodeAddresses :many
SELECT node_id, address_type, address
FROM node_addresses
WHERE node_id = $1
`

func (q *Queries) GetNodeAddresses(ctx context.Context, nodeID int64) ([]NodeAddress, error) {
	rows, err := q.db.QueryContext(ctx, getNodeAddresses, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeAddress
	for rows.Next() {
		var i NodeAddress
		if err := rows.Scan(&i.NodeID, &i.AddressType, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeAliasByPubKey = `-- name: GetNodeAliasByPubKey :one
SELECT alias
FROM nodes
WHERE pub_key = $1
`

func (q *Queries) GetNodeAliasByPubKey(ctx context.Context, pubKey []byte) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getNodeAliasByPubKey, pubKey)
	var alias sql.NullString
	err := row.Scan(&alias)
	return alias, err
}

const getNodeByPubKey = `-- name: GetNodeByPubKey :one
SELECT id, pub_key, block_height, alias, serialised_announcement
FROM nodes
WHERE pub_key = $1
`

func (q *Queries) GetNodeByPubKey(ctx context.Context, pubKey []byte) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByPubKey, pubKey)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.PubKey,
		&i.BlockHeight,
		&i.Alias,
		&i.SerialisedAnnouncement,
	)
	return i, err
}

const getNodeFeatures = `-- name: GetNodeFeatures :many
SELECT node_id, feature
FROM node_features
WHERE node_id = $1
`

func (q *Queries) GetNodeFeatures(ctx context.Context, nodeID int64) ([]NodeFeature, error) {
	rows, err := q.db.QueryContext(ctx, getNodeFeatures, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeFeature
	for rows.Next() {
		var i NodeFeature
		if err := rows.Scan(&i.NodeID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeIDByPubKey = `-- name: GetNodeIDByPubKey :one
SELECT id
FROM nodes
WHERE pub_key = $1
`

func (q *Queries) GetNodeIDByPubKey(ctx context.Context, pubKey []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNodeIDByPubKey, pubKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIPV4NodeAddress = `-- name: InsertIPV4NodeAddress :exec
INSERT INTO node_addresses (
    node_id, address_type, address
) VALUES (
    $1, 0, $2
)
`

type InsertIPV4NodeAddressParams struct {
	NodeID  int64
	Address string
}

func (q *Queries) InsertIPV4NodeAddress(ctx context.Context, arg InsertIPV4NodeAddressParams) error {
	_, err := q.db.ExecContext(ctx, insertIPV4NodeAddress, arg.NodeID, arg.Address)
	return err
}

const insertIPV6NodeAddress = `-- name: InsertIPV6NodeAddress :exec
INSERT INTO node_addresses (
    node_id, address_type, address
) VALUES (
   $1, 1, $2
)
`

type InsertIPV6NodeAddressParams struct {
	NodeID  int64
	Address string
}

func (q *Queries) InsertIPV6NodeAddress(ctx context.Context, arg InsertIPV6NodeAddressParams) error {
	_, err := q.db.ExecContext(ctx, insertIPV6NodeAddress, arg.NodeID, arg.Address)
	return err
}

const insertNode = `-- name: InsertNode :one
INSERT INTO nodes (
    pub_key, block_height, alias,  serialised_announcement
) VALUES (
    $1, $2, $3, $4
) RETURNING id
`

type InsertNodeParams struct {
	PubKey                 []byte
	BlockHeight            sql.NullInt32
	Alias                  sql.NullString
	SerialisedAnnouncement []byte
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertNode,
		arg.PubKey,
		arg.BlockHeight,
		arg.Alias,
		arg.SerialisedAnnouncement,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertNodeFeature = `-- name: InsertNodeFeature :exec
INSERT INTO node_features (
    node_id, feature
) VALUES (
    $1, $2
)
`

type InsertNodeFeatureParams struct {
	NodeID  int64
	Feature int32
}

func (q *Queries) InsertNodeFeature(ctx context.Context, arg InsertNodeFeatureParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeFeature, arg.NodeID, arg.Feature)
	return err
}

const insertTorV3NodeAddress = `-- name: InsertTorV3NodeAddress :exec
INSERT INTO node_addresses (
    node_id, address_type, address
) VALUES (
    $1, 2, $2
)
`

type InsertTorV3NodeAddressParams struct {
	NodeID  int64
	Address string
}

func (q *Queries) InsertTorV3NodeAddress(ctx context.Context, arg InsertTorV3NodeAddressParams) error {
	_, err := q.db.ExecContext(ctx, insertTorV3NodeAddress, arg.NodeID, arg.Address)
	return err
}

const updateNode = `-- name: UpdateNode :exec
UPDATE nodes
SET block_height = $2,
    alias = $3,
    serialised_announcement = $4
WHERE id = $1
`

type UpdateNodeParams struct {
	ID                     int64
	BlockHeight            sql.NullInt32
	Alias                  sql.NullString
	SerialisedAnnouncement []byte
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) error {
	_, err := q.db.ExecContext(ctx, updateNode,
		arg.ID,
		arg.BlockHeight,
		arg.Alias,
		arg.SerialisedAnnouncement,
	)
	return err
}
