name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  merge_group:
    branches:
      - "master"

concurrency:
  # Cancel any previous workflows if they are from a PR or push.
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  BITCOIN_VERSION: "28"
  
  # TRANCHES defines the number of tranches used in the itests.
  TRANCHES: 16

  # SMALL_TRANCHES defines the number of tranches used in the less stable itest
  # builds
  #
  # TODO(yy): remove this value and use TRANCHES.
  SMALL_TRANCHES: 8

  # If you change this please also update GO_VERSION in Makefile (then run
  # `make lint` to see where else it needs to be updated as well).
  GO_VERSION: 1.23.6

jobs:
  ########################
  # run unit tests
  ########################
  unit-test:
    name: run unit tests
    runs-on: ubuntu-latest
    strategy:
      # Allow other tests in the matrix to continue if one fails.
      fail-fast: false
      matrix:
        unit_type:
          - btcd unit-cover

    steps:
      - name: cleanup space
        run: rm -rf /opt/hostedtoolcache

      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fetch and rebase on ${{ github.base_ref }}
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/rebase

      - name: git checkout fuzzing seeds
        uses: actions/checkout@v4
        with:
          repository: lightninglabs/lnd-fuzz
          path: lnd-fuzz

      - name: rsync fuzzing seeds
        run: rsync -a --ignore-existing lnd-fuzz/ ./

      - name: setup go ${{ env.GO_VERSION }}
        uses: ./.github/actions/setup-go
        with:
          go-version: '${{ env.GO_VERSION }}'
          key-prefix: unit-test

      - name: install bitcoind
        run: ./scripts/install_bitcoind.sh $BITCOIN_VERSION

      - name: run ${{ matrix.unit_type }}
        run: make ${{ matrix.unit_type }}

      - name: Send coverage
        uses: ziggie1984/actions-goveralls@c440f43938a4032b627d2b03d61d4ae1a2ba2b5c
        if: matrix.unit_type == 'btcd unit-cover'
        continue-on-error: true
        with:
          path-to-profile: coverage.txt
          flag-name: 'unit'
          parallel: true


  ########################
  # run integration tests with TRANCHES
  ########################
  basic-integration-test:
    name: basic itests
    runs-on: ubuntu-latest
    if: '!contains(github.event.pull_request.labels.*.name, ''no-itest'')'
    strategy:
      # Allow other tests in the matrix to continue if one fails.
      fail-fast: false
      matrix:
        include:
          - name: btcd
            args: backend=btcd cover=1
          - name: bitcoind
            args: backend=bitcoind cover=1

    steps:
      - name: cleanup space
        run: rm -rf /opt/hostedtoolcache

      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fetch and rebase on ${{ github.base_ref }}
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/rebase

      - name: setup go ${{ env.GO_VERSION }}
        uses: ./.github/actions/setup-go
        with:
          go-version: '${{ env.GO_VERSION }}'
          key-prefix: integration-test

      - name: install bitcoind
        run: ./scripts/install_bitcoind.sh $BITCOIN_VERSION

      - name: run ${{ matrix.name }}
        run: make itest-parallel tranches=${{ env.TRANCHES }} ${{ matrix.args }} shuffleseed=${{ github.run_id }}${{ strategy.job-index }}

      - name: Send coverage
        if: ${{ contains(matrix.args, 'cover=1') }}
        continue-on-error: true
        uses: ziggie1984/actions-goveralls@c440f43938a4032b627d2b03d61d4ae1a2ba2b5c
        with:
          path-to-profile: coverage.txt
          flag-name: 'itest-${{ matrix.name }}'
          parallel: true

      - name: Zip log files on failure
        if: ${{ failure() }}
        timeout-minutes: 5 # timeout after 5 minute
        run: 7z a logs-itest-${{ matrix.name }}.zip itest/**/*.log itest/postgres.log

      - name: Upload log files on failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: logs-itest-${{ matrix.name }}
          path: logs-itest-${{ matrix.name }}.zip
          retention-days: 5

  ########################
  # Backwards Compatibility Test
  ########################
  backwards-compatability-test:
    name: backwards compatability test
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🛡️ backwards compatibility test
        run: make backwards-compat-test

  # Notify about the completion of all coverage collecting jobs.
  finish:
    if: ${{ always() }}
    needs: [unit-test, basic-integration-test]
    runs-on: ubuntu-latest
    steps:
      - name: Send coverage
        uses: ziggie1984/actions-goveralls@c440f43938a4032b627d2b03d61d4ae1a2ba2b5c
        continue-on-error: true
        with:
          parallel-finished: true
