name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  merge_group:
    branches:
      - "master"

concurrency:
  # Cancel any previous workflows if they are from a PR or push.
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  BITCOIN_VERSION: "28"
  
  # TRANCHES defines the number of tranches used in the itests.
  TRANCHES: 16

  # SMALL_TRANCHES defines the number of tranches used in the less stable itest
  # builds
  #
  # TODO(yy): remove this value and use TRANCHES.
  SMALL_TRANCHES: 8

  # If you change this please also update GO_VERSION in Makefile (then run
  # `make lint` to see where else it needs to be updated as well).
  GO_VERSION: 1.23.6

jobs:
  backwards-compatability-test:
    name: Backwards Compatability Check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🛡️ Backwards Compatibility Test
        run: make backwards-compat-test

